### ISSUE TITLE
Not working in Obsidian v0.14.5

### ISSUE THREAD

**Issue by JohnMarkHowell** [efemkay/obsidian-modular-css-layout#1]
I dropped the three CSS files into the [vault]\.obsidian\snippet folder, enabled the CSS snippets in Settings/CSS snippets, and ensured that Readable Line Length was off. I also add the 'Contextual Typography' plug-in. I copied the md example you had in your README.MD and it still displays three in a stack.

> [!three-column]
> 
>> [!note]+ Work
>> your notes or lists here. using markdown formatting
>
>> [!warning]+ Personal
>> your notes or lists here. using markdown formatting
>
>> [!summary]+ Charity
>> your notes or lists here. using markdown formatting

**Comment by efemkay** [comment]
omg. u r right. sorry i forgot to update the readme on this. i change the callout name after i discovered that there's no need for me to specify how many columns explicit. use [!multi-column] instead and put as many sub-callout u need. i have a style settings to specify min width. if u put 2 sub-callout, it will expand to fill in the space, but if u put too many it will just flow to next row.

anyway, the example should read like below
```
> [!multi-column]
>
>> [!note]+ Work
>> your notes or lists here. using markdown formatting
>
>> [!warning]+ Personal
>> your notes or lists here. using markdown formatting
>
>> [!summary]+ Charity
>> your notes or lists here. using markdown formatting
```
![image](https://user-images.githubusercontent.com/42369515/163736259-9819cba6-e7aa-4077-b578-7a93aebe1a30.png)

let me know if this fix it.

**Comment by JohnMarkHowell** [comment]
You rock, @efemkay!!! It works great! Thank you for such an amazingly quick response!!
And thank you for clarifying that the CT plugin was not needed. I try not to have any plugins that I do not need!

Great work!!
