### ISSUE TITLE
If i don't use the wide-page caaclass zhe default view is also wide.

### ISSUE THREAD

**Issue by PencilMing** [efemkay/obsidian-modular-css-layout#11]
![widepage](https://user-images.githubusercontent.com/82462283/170804758-3857ddd8-b5e7-49d7-a0b3-2a568e6dec2a.gif)
First of all, this CSS is awesome I like it. But I find there is a narrow mode in the setting, but the narrow mode isn't the default view. I have to choose one type in CSS class to let narrow view work, could you add a new CSS class as narrow-page or some other. I want to use it instead of "Readable in length" mode. Thank you.

**Comment by efemkay** [comment]
yeah. the narrow mode settings is to be used with `wide-<block/page>`. if i understand u correctly, you wanted to disable RLL in obsidian and instead use css class to control which note has narrow mode. is that correct? i guess i can add that option

**Comment by PencilMing** [comment]
yes~

**Comment by efemkay** [comment]
i've updated the snippet with the requested feature. u can disable RLL in your vault and use `narrow-page` to control selected note/page for "narrow" width.

do let me know if it works on your side

**Comment by PencilMing** [comment]
Yes，it's work～Thank you！
