### ISSUE TITLE
Multi-Column not working in new Vault

### ISSUE THREAD

**Issue by nousernameavailableanymore** [efemkay/obsidian-modular-css-layout#13]
My initial issue is that multi-column callouts dont seem to work as intended in my productive vault.
All testing was done with Live Preview (reading mode is kind of obsolete now).
I used the latest multi-column CSS snippet with Obsidian 0.14.6 (latest official version).

This callout block:
```
> [!multi-column]
> 
>> [!note]+ Work
>> your notes or lists here. using markdown formatting
>
>> [!warning]+ Personal
>> your notes or lists here. using markdown formatting
>
>> [!blank-container]
>> your notes or lists here. using markdown formatting
```
will produce this result:
![image](https://user-images.githubusercontent.com/45376324/170897780-4c777ea2-1e23-495c-b8f0-77e2a951fae0.png)
It creates two instead of the intended three columns and the blank-container callout is not blank.

HOWEVER, for troubleshooting, I set up a new, fresh vault from scratch.
I copied all three CSS snippets to the snippets folder and enabled them.

In the new test vault, the multi column flat out does not work at all.

This callout
```
> [!multi-column]
> 
>> [!note]+ Work
>> your notes or lists here. using markdown formatting
>
>> [!warning]+ Personal
>> your notes or lists here. using markdown formatting
>
>> [!summary]+ Charity
>> your notes or lists here. using markdown formatting
```
produces this result
![image](https://user-images.githubusercontent.com/45376324/170897921-0719cf7c-2e44-4358-b4a1-23231195d8ca.png)

**Comment by efemkay** [comment]
hmm... my guess would be perhaps u missed to enable the snippet in the new vault. see my gif here for reference

https://github.com/efemkay/obsidian-modular-css-layout/blob/main/docs/assets/how%20to%20install%20and%20enable%20MCL.gif

- it has feature to set the width of the callout, by default it require min of 200px, so if the screen is squeezed, it will flow to next row
    - ![image](https://user-images.githubusercontent.com/42369515/170996138-04ee39b2-28bc-4ef0-833d-bfbb68abc49c.png)
- but if u okay with sub callout squeezed even at smaller screen, u can set using Style Settings plugin. if u have space, it will expand to fill the space available
    - ![image](https://user-images.githubusercontent.com/42369515/170996236-1ed39613-938d-4582-951e-150ba4780e62.png)

let me know if this fixes your issues.

**Comment by nousernameavailableanymore** [comment]
Update:
hmmm this was probably an issue on my side although I m still trying to find out, why this occurs.

So when I go to here:
https://github.com/efemkay/obsidian-modular-css-layout
and right click on the MCL Multi Column.css, then "Save Link as", it will download a file called MCL Multi Column.css. However, this looks completely different from the actual file.

So I guess this was just me using github wrong, but still very confusing, as it would download a file with the correct name.
