### ISSUE TITLE
No configuration available in Style Settings plugin for multi column CSS snippet

### ISSUE THREAD

**Issue by nousernameavailableanymore** [efemkay/obsidian-modular-css-layout#14]
Style Settings Plugin Version: 0.4.10 (latest)
Obsidian Version: 0.14.6 (latest official)

The readme file states that
> (can be change using Sytle Settings plugin).

I tried:
- copying only the Multi Column CSS snippet into snippet folder of existing vault
- copying all three CSS snippets into the snippet folder of a completely new vault
In both cases, no configuration options showed up in Style Settings Plugin.

**Comment by efemkay** [comment]
- here's a gif to guide how the Style Settings plugin works with MCL.
    - https://raw.githubusercontent.com/efemkay/obsidian-modular-css-layout/main/docs/assets/how%20to%20install%20and%20enable%20MCL.gif
- here's a screenshot for quick glance
    -  ![screenshot 442](https://user-images.githubusercontent.com/42369515/170997074-b4643ab7-a060-4d1e-b46b-535db3b58348.png)

let me know if this fixes your issue

**Comment by nousernameavailableanymore** [comment]
Update:
hmmm this was probably an issue on my side although I m still trying to find out, why this occurs.

So when I go to here:
https://github.com/efemkay/obsidian-modular-css-layout
and right click on the MCL Multi Column.css, then "Save Link as", it will download a file called MCL Multi Column.css. However, this looks completely different from the actual file.

So I guess this was just me using github wrong, but still very confusing, as it would download a file with the correct name.
