### ISSUE TITLE
Narrowing dataview blocks

### ISSUE THREAD

**Issue by abers** [efemkay/obsidian-modular-css-layout#17]
Unsure if this is already possible and/or I am doing something wrong. I am trying to set up multiple columns with dataviews creating a list in each. However, the width of the dataview blocks make it so only two columns will display at most. And that's with both sidebars hidden. Any less space and it collapses into a single column. This seems to be a result of dataviews having a fixed width. Is there a way to override that for the page, so that their width is more responsive? I am using the Minimal theme.

**Comment by efemkay** [comment]
Hi @abers , my multi column was designed to be responsive but i do specify min width of 200px and allow the content to sort of dictate the width they require. I haven't tried with very wide dataview table - is that your case? Having a number of table columns. A redacted/garbled screenshot would help me get some picture of it

**Comment by abers** [comment]
My case is dataview lists, so technically one column. Though, that turns out to be the root of the issue, with the CSS dataview tables are responsive, but dataview lists are still fixed at the theme defined block width.

**Comment by efemkay** [comment]
@abers i fixed with v0.4.1. do have a try to see if it solves your part

**Comment by efemkay** [comment]
implemented in [v0.4.1](https://github.com/efemkay/obsidian-modular-css-layout/releases/tag/0.4.1)
