### ISSUE TITLE
How to apply this globally?

### ISSUE THREAD

**Issue by Miigon** [efemkay/obsidian-modular-css-layout#19]
I would like to know how to apply wide views across all the notes without specifying cssClass in every single one. Thanks!

**Comment by efemkay** [comment]
@Miigon do u mean wide-table or wide-dataview? If so, i don't have that feature (yet). If u mean wide-page, u can simply disable Readable line length (obsidian built-in option) from Settings > Editor > Display.

**Comment by Miigon** [comment]
I meant wide-table and wide-dataview. But still thanks for your reply and your great project! 

(obsidian devs should really just add these features to obsidian. large mermaid graphs are just unusable right now.)

**Comment by efemkay** [comment]
i reopen this as it's a valid FR. will update once i get it working satisfactorily

**Comment by efemkay** [comment]
implemented in https://github.com/efemkay/obsidian-modular-css-layout/releases/tag/0.5.0
