### ISSUE TITLE
Live Preview float doesn't work in Minimal theme: width and margins not respected

### ISSUE THREAD

**Issue by gtg922r** [efemkay/obsidian-modular-css-layout#23]
Absolutely love this snippet, thanks so much for publishing it. I'm using it extensively for multiple columns and really hoping I can use it for infobox style callouts in Live Preview with Minimal.

Currently in Live Preview, with Minimal theme, `float-right-small` (or any size) doesn't quite work because 1: the width isn't respected (callout is full width) and 2: the callout sits on the far right of the view pane, out of line with the rest of the content:

<img width="1068" alt="Screenshot 2022-11-19 at 10 00 28 AM" src="https://user-images.githubusercontent.com/1195174/202865568-0347e3b3-f389-40ca-bbde-aaab6eac7747.png">

The problem of right alignment only gets worse as the window gets wider. 

Note: this is in a clean vault with only Minimal and Contextual Typography installed, on MacOS.

Here is the source for the above:
![Screenshot 2022-11-19 at 10 15 33 AM](https://user-images.githubusercontent.com/1195174/202865614-29cc69af-a3b6-46a3-b886-d8548836841d.png)

As exepected, things generally work with the default theme:
<img width="1068" alt="Screenshot 2022-11-19 at 10 04 40 AM" src="https://user-images.githubusercontent.com/1195174/202865676-9ab47dda-b50f-4a4d-a34b-9ee71ed3a7a2.png">

Also, if you use `wide-page`, everything works quite nicely with Minimal Theme in Live Preview, including respecting the size:
 
![Screenshot 2022-11-19 at 10 10 39 AM](https://user-images.githubusercontent.com/1195174/202865724-4cd83492-a280-46e8-aa79-634b4717ecbb.png)

**Comment by efemkay** [comment]
tqs for raising the issue. yeah i can repro it. i have a fix it but wanted to test it further, i'll release it soon.

**Comment by efemkay** [comment]
close as the fixed released earlier. do update if somehow the issue persists
