### ISSUE TITLE
Bug: {.three-column-list-block} artefacts on lists

### ISSUE THREAD

**Issue by spiritualgeek** [efemkay/obsidian-modular-css-layout#26]
There are some strange artefacts occurring when utilising the  `{.[two|three]-column-list-block}` functionality

**Graphic showing what is looks like**
![58411](https://user-images.githubusercontent.com/53917562/210167587-3963a813-7925-4a70-b1b4-e81e9d7a1a9d.png)

**Example that can be used to reproduce**
```
- **A section**
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
- **A section**
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
- **A section**
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
- **A section**
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
- **A section**
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
- **A section**
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
- **A section**
	- An item which is but an item
	- An item which is but an item
	- An item which is but an item
{.three-column-list-block}
```

Furthermore, you utilise this twice on the same page it seems to just not work at all

Does with default theme as well

Thanks

**Comment by spiritualgeek** [comment]
Just an update. 

`#mcl/list-card` seems to be the best alternative, but I prefer `{.three-column-list-block}`

PS: A `{.four-column-list-block}` would also be welcome :)

**Comment by efemkay** [comment]
when using markdown attributes custom classes like the one i use `{.three-column-list-block}` it has limitation when the last list item is indented. it stems from how obsidian expect a empty line after a list (u can test with simple example below).

anyway, there's also `#mcl/list-column` that's closer to columns per example u stated. `#mcl/list-card` uses grid like structure left to right first then flow next line. `#mcl/list-column` doesn't specify column as it depends on the min-width u define (default is 200px), but anyway i think i can introduce 3- or 4- columns using `#mcl/list-xxx`

i'll keep this open until i have that implemented

```
- main bullet 1
- main bullet 2
	- sub one
	- sub two
paragraph without empty line after list
```

**Comment by spiritualgeek** [comment]
Quick update - `#mcl/list-column` works fine, and the last section is "picked" up, but I still have the issue with the first column not rendering bullets properly

**Comment by efemkay** [comment]
@spiritualgeek i've released 0.8.1 that fixed the first column bullets not rendering properly.

on the use of tag `#mcl/list-column`, it was MCL relatively newer feature but i would recommend that more for the following reason
- it relies on Contextual Typography plugin which is more broadly useful for other use outside of MCL (some themes also recommend using it for some styling). Markdown Attributes is a bit niche but useful (or familiar) if u used to gh pages and jekyll
- in future, i can do this without any plugin by relying on `:has()` which just need majority obsidian users to update their installer to v1.1.9 or higher
- it didn't disrupt the last section as u mentioned because i can place it almost anywhere. Markdown Attributes require specific placement for the classes

**Comment by spiritualgeek** [comment]
Thanks - I updated, but it still seems to be doing it with the first column?

Appreciate the info and update

**Comment by efemkay** [comment]
Ok that's weird, can u help me out a bit
- what theme is this affecting? Does it affect when in default theme as well?
- if above is true, can u try with all other CSS snippets disabled.

The only reason I can think of is that some other CSS might have higher priority than my fix.

**Comment by spiritualgeek** [comment]
I have been hectic, sorry

All snippets off and it still does it. Also in restricted mode as you can see in the image

![45974](https://user-images.githubusercontent.com/53917562/213250836-68916cd6-04c7-422a-84cf-78faf652563d.png)

**Comment by efemkay** [comment]
Hey @spiritualgeek I think I fully fixed this. Lemme know if this still an issue on ur side.

**Comment by efemkay** [comment]
i'll mark this as closed. if issue still persist, you may open up new issue
