### ISSUE TITLE
Incorrect padding for embedded multi-column callouts

### ISSUE THREAD

**Issue by serpro69** [efemkay/obsidian-modular-css-layout#30]
here's a screenshot showing a multi-column and a regular callout

![image](https://user-images.githubusercontent.com/22973227/219071772-a641d3d7-d2e4-4c96-a5b7-77fb99280e77.png)

**Comment by efemkay** [comment]
hi there. what theme is that? or if it's snippet can u share to help me reproduce. i think i know what's causing it. need to inspect in detail

**Comment by serpro69** [comment]
The theme is minimal. It looks similar to https://github.com/kepano/obsidian-minimal/issues/523, which was fixed in the theme itself, and seems like it might need to be applied to your snippets also?

**Comment by efemkay** [comment]
Fixed it with v0.9.0. let me know if this is still an issue

**Comment by serpro69** [comment]
Looks great. Thanks!
