### ISSUE TITLE
Multi column list grid is broken with last update

### ISSUE THREAD

**Issue by oliviercarizzoni** [efemkay/obsidian-modular-css-layout#34]
The following snippet taken from documentation no longer works:

```
- #### Core Work #mcl/list-grid 
    - [[00 Home|Main Goal 1]]
    - [[00 Home|Main Goal 1]]
    - [[00 Home|Main Goal 1]]
        - Collaboration with Jane
    - [[00 Home|Main Goal 1]]
- #### Learning & System
    - [[00 Home|Learning Goal 1]]
    - [[00 Home|Initiative 1]]
    - [[00 Home|Initiative 2]]
- #### Personal
    - [[00 Home|Personal Goal 1]]
    - [[00 Home|Personal Goal 2]]
```

## Current version

![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/36270849/51933120-f1b2-483c-ac63-1b5f92ca89e6)

## Previous version

![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/36270849/d9a5471e-57c5-49b0-93cc-90f2ebbf2842)

**Comment by efemkay** [comment]
@oliviercarizzoni just to confirm, when u say updated, u mean the snippets right? (coz the obsidian also just had a public release as well)

if so, most likely you have obsidian with previous installer. the latest snippet require installer to be v1.1.9 or higher as i now use the new css `:has()` selector (you would need to redownload obsidian installer from their website and just rerun it. do backup your files.

for clarity, in the obsidian's About section, you can see the following screenshot. note that there's two version appear there. it's important the bottom one says v1.1.9 or higher
![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/42369515/9e6f51f3-f9eb-49fb-b101-48b5099da796)

let me know if this doesn't resolve your issue

**Comment by oliviercarizzoni** [comment]
Thanks for your detailed answer, I will check that and make some tests and get back to you asap !

Regards, Olivier

**Comment by efemkay** [comment]
i'm marking this as closed. do open up new issue if somehow it persists

**Comment by efemkay** [comment]
@ssemenova can u give a screenshot of the raw markdown. preferably like mine below

but in case u missed the docs, here are few notes
1) it works only in reading view. obsidian has 3 view states editing view (i.e. source mode and live preview) and reading view. https://help.obsidian.md/Editing+and+formatting/Editing+and+previewing+Markdown#Live+Preview
2) if you want it to work in Live Preview, then you would have to wrap it in blank callout https://efemkay.github.io/obsidian-modular-css-layout/multi-column/04-blank-callout/

![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/42369515/2fdf83a8-13e8-4521-92fe-60921936b4ca)

**Comment by ssemenova** [comment]
Thank you for getting back to me! Here it is in live preview:

<img width="775" alt="Screen Shot 2023-08-17 at 1 53 31 PM" src="https://github.com/efemkay/obsidian-modular-css-layout/assets/6182097/ea8d63a2-9240-4d73-8049-2d9ac24ee19d">

And in reading mode:

<img width="887" alt="Screen Shot 2023-08-17 at 1 53 39 PM" src="https://github.com/efemkay/obsidian-modular-css-layout/assets/6182097/46ffd9fe-fc1b-4e92-94d3-f4e316be569c">

**Comment by oliviercarizzoni** [comment]
I no longer have the problem, seems to be fixed for me.

Something odd seeing the screenshot: have you stretched the window enough to have blocs side by side ?

Otherwise maybe you should try incrementally: deactivate plugins and theme and css snippets and then test step by step ! Let us know
