### ISSUE TITLE
Using # headings as titles for the columns is not evenly distr

### ISSUE THREAD

**Issue by Hexara7777** [efemkay/obsidian-modular-css-layout#35]
As the title says, when I use a callout as the type of the column, it works properly but if I use # Heading instead they're not evenly distributed among the page width:
![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/130001839/1a577186-9070-46c3-9987-09ced333fccc)

```
> [!multi-column]
>
>> # Work
>> sadas
>
>> # Personal
>> your notes or lists here. using markdown formattingasdasdasdasd
>
>># Charity
>> your notes or lists here. using markdown formattingsadasdasd
>
>> # Test
>> dsadas
>> asdsad
```

```
> [!multi-column]
> 
>> [!note]+ Work
>> - your notes or lists here. using markdown formatting
>
>> [!warning]+ Personal
>> your notes or lists here. using markdown formatting
>
>> [!summary]+ Charity
>> your notes or lists here. using markdown formatting
```

**Comment by efemkay** [comment]
yeap. what u have there is blockquotes within the `multi-column` callout. i didn't code that in. so far only callouts within `multi-column` callout. but i think should be no issue for me to make enhancement on that

**Comment by SaifEl-Deen** [comment]
@efemkay Thank you for your fast response, I just wonder how is this different to what is seen here on the view below? Pardon me, I have zero knowledge in these stuff. 
![163700561-c8d62aa3-0ac8-488c-a80e-8bfb3b539ca8](https://github.com/efemkay/obsidian-modular-css-layout/assets/130001839/8db651d3-b7aa-4d8e-9072-8c53fb0ab9c1)

**Comment by efemkay** [comment]
@SaifEl-Deen , for the bottom part of the example, the markdown is as per below -- it's using a custom callout in my MCL snippets i.e. `[!blank-container]` for invisible callout. on that note, i think i'll update the docs to be clearer.

```md
> [!multi-column]
> 
>> [!blank-container]+
>> ### Work
>> - [[Obsidian/Modular Layout|Project A]]
>> - [[Obsidian/Modular Layout|Project B]]
>> - [[Obsidian/Modular Layout|Project C]]
>
>> [!blank-container]+
>> ### Family
>> - [[Obsidian/Modular Layout|Area A]]
>> - [[Obsidian/Modular Layout|Area B]]
>> - [[Obsidian/Modular Layout|Area C]]
>
>> [!blank-container]+
>> ### Hobby
>> - [[Obsidian/Modular Layout|Activity A]]
>> - [[Obsidian/Modular Layout|Activity B]]
```

**Comment by SaifEl-Deen** [comment]
That's a bit complicated to do, why is that Obsidian/Module Layout thing repeated before each entry?

**Comment by efemkay** [comment]
enhanced with v0.9.7
