### ISSUE TITLE
Weird images on Minimal Theme with "MCL Gallery Cards" snippet

### ISSUE THREAD

**Issue by Rikiub** [efemkay/obsidian-modular-css-layout#36]
*First, I will say that I love your snippets! They bring my Obsidian notes to life!*

But... recently "MCL Gallery Cards" has issues when I use it with the [Minimal Theme](https://github.com/kepano/obsidian-minimal). 

**Issues like:**

## Big images in live preview

**Minimal Theme**
![Obsidian 20230526231059](https://github.com/efemkay/obsidian-modular-css-layout/assets/114118274/b4140834-6c1e-44f5-8634-2ff75fbb403b)

**Default Theme (Expected)**
![Obsidian 20230526231111](https://github.com/efemkay/obsidian-modular-css-layout/assets/114118274/4746edfe-21cb-40f5-9e69-7b5bde36713a)

## Right-Left bugs

**Minimal Theme (Live preview)**
![Obsidian 20230526231130](https://github.com/efemkay/obsidian-modular-css-layout/assets/114118274/93295154-e16d-4f77-989b-6b87ca252d15)

**Minimal Theme (Reading view)**
![Obsidian 20230526231140](https://github.com/efemkay/obsidian-modular-css-layout/assets/114118274/c6d694e1-3886-4984-8b02-0379c59efeb1)

**Default Theme (Expected)**
![Obsidian 20230526231150](https://github.com/efemkay/obsidian-modular-css-layout/assets/114118274/0ecad94d-f7d5-45bb-8c4d-597f29011188)

**Comment by efemkay** [comment]
@Rikiub, Yup. that's indeed a bug. i've published [0.9.2](https://github.com/efemkay/obsidian-modular-css-layout/releases/tag/0.9.2) and that should fix it.

on that note if you want to have the float also works in live preview the syntax should be `[[filename.jgp|float-right|300]]`. if you don't have the `float` word i.e. `[[filename.jpg|right|300]]` it will only works in reading view. the reason being, editing still isn't ideal when you use float but float-right is ok (when text is on the left, selecting and editing text is still fine)

**Comment by Rikiub** [comment]
The **"Big images in live preview"** is fixed, excelent!

But **"Right-Left bugs"** still have bugs. Maybe is a issue with the [Minimal Theme](https://github.com/kepano/obsidian-minimal)? This don't happen with others themes, only with that theme.

**Comment by efemkay** [comment]
When using minimal theme, u have to enter `cssclass: minimal-float` in the frontmatter. It's a workaround I have to employ because how minimal changes quite a number of things.

Btw, this is how u do so
```
---
cssclass: minimal-float
---

The rest of your content 
```

**Comment by Rikiub** [comment]
Ah, I see, It's working again.

Thanks to reply! So I close this issue.
