### ISSUE TITLE
File Explorer Highlighting 

### ISSUE THREAD

**Issue by ShreyaPatibanda** [efemkay/obsidian-modular-css-layout#38]
when I toggle on the multi-callout snippet, when I hover over the file explorer on the left, it doesn't highlight the whole bar, it just highlights based on the title size.

https://github.com/ckRobinson/multi-column-markdown/assets/73957016/f99378af-7a07-4cf1-9d8d-57716b45c749

**Comment by efemkay** [comment]
hi there @ShreyaPatibanda i cannot repro that. need ur help to rule out certain things first. can u
1. update the snippets to the latest (just in case)
2. check and share what's your obsidian installer version
    - ![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/42369515/1ea395d9-e38e-4b32-b2b5-b0b1a3055d65)

**Comment by ShreyaPatibanda** [comment]
I just updated it to the latest (it says it was last committed June 24) and issue no longer applies. Thanks. Marking this as closed
