### ISSUE TITLE
FR: blank line should always count as column divider

### ISSUE THREAD

**Issue by nousernameavailableanymore** [efemkay/obsidian-modular-css-layout#41]
A blank line in a "multi-column" admonition should always split the contens into a new column.
This already works with "normal" paragraphs (not list) but there the margins seem to be wrong.

This will produce a two column list:
````
```ad-multi-column
Test 1 
Test 2
Test 3

Test 4
Test 5
```
````
![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/45376324/3bc84ac2-4479-4c32-8b9a-026308ebc4bc)

While this will not:
````
```ad-multi-column
- Test 1 
- Test 2
- Test 3

- Test 4
- Test 5
```
````
![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/45376324/d75a136c-9b18-4546-9073-c067e31d0346)

Please make blank lines behave consistently and always act as seperator between columns.

**Comment by efemkay** [comment]
enhanced with v0.9.7
