### ISSUE TITLE
Turn on the CSS snippet, will affect the table width of the minimal theme

### ISSUE THREAD

**Issue by MugenLee** [efemkay/obsidian-modular-css-layout#45]
Problem Description：
When I use the minimal theme of v7.0.7 and set cssclass: table-wide in yaml, if 「MCL Gallery Cards.css」and 「 MCL Multi Column.css」 is turned on at the same time, table-wide will not work

According to my test, any opening of these two snippets will cause this problem. Only when they are closed at the same time can this problem be solved.

I recorded the corresponding animation, please check

![动画](https://github.com/efemkay/obsidian-modular-css-layout/assets/91043731/7c14e18a-8e5e-4cd1-a668-3176346b19be)

I like minimal and your CSS snippets very much. They are widely used in my OB system. Please be sure to solve this problem. If you have any questions, please feel free to contact me

expecting your reply

**Comment by efemkay** [comment]
@MugenLee i've identified the issue. i guess i was too eager to remove the need to specify the `minimal-float` for float callout that the snippet inadvertently, disrupt minimal own wide table settings.

i will release fix soon

**Comment by MugenLee** [comment]
> @MugenLee i've identified the issue. i guess i was too eager to remove the need to specify the `minimal-float` for float callout that the snippet inadvertently, disrupt minimal own wide table settings.
> 
> i will release fix soon

great!
In addition, when I was using the latest version of OB v1.4, I found that after opening the new  properties, it is smaller than the width of the text below

also  to look at together
![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/91043731/f22a5d5e-5813-4033-8657-3b09bec3474b)
![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/91043731/b29450eb-0284-412b-934a-b6fe2ef67697)

**Comment by efemkay** [comment]
i've released a fix. do have a test on it

**Comment by MugenLee** [comment]
> i've released a fix. do have a test on it

Wonderful~
thx so much~
