### ISSUE TITLE
Recommendations now that Snippet Downloader is Archived

### ISSUE THREAD

**Issue by etsai** [efemkay/obsidian-modular-css-layout#47]
<img width="1179" alt="image" src="https://github.com/efemkay/obsidian-modular-css-layout/assets/1137295/b3859acf-c59e-43a0-942f-cfcd3ef62ab9">

Now that snippet downloader is archived, what steps would you recommend?

**Comment by efemkay** [comment]
hey @etsai thanks for bringing this to my attention. didn't realise the plugin is now archived. i think there's a few plugins that can take its place but i haven't checked on them. for now i suggest you download them manually first. follow the steps below
1. Go to https://github.com/efemkay/obsidian-modular-css-layout/releases
2. Under the latest release, look under Asset, there should be a zip file named "MCL-snippets-0.9.5.zip"
3. Download the file and extract the content to your Obsidian's snippet folder e.g. `<vault>\.obsidian\snippets`
4. Refresh Obsidian and you should see the snippets as part of Settings > Appearance > CSS Snippets

![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/42369515/06bf573e-6daf-45e7-af57-71d33f05811a)

> there's also a step in my docs page for this
> https://efemkay.github.io/obsidian-modular-css-layout/installation/#manually-saving-from-gh

**Comment by efemkay** [comment]
i've updated the installation doc page (see https://efemkay.github.io/obsidian-modular-css-layout/installation/). unfortunately, for now, the most user friendly way to handle MCL installation (and updates) is via the plugin. But users can install it via BRAT plugin (additional steps required, but it's a compromise i think worth it for the ease of later update process)
