### ISSUE TITLE
Multi-column broken with Minimal Theme

### ISSUE THREAD

**Issue by Rikiub** [efemkay/obsidian-modular-css-layout#49]
_This is a multi-column by 3x3_

### Default Theme (Expected)
![Default Theme](https://github.com/efemkay/obsidian-modular-css-layout/assets/114118274/4be67c62-bd1b-4b76-8b17-c14df8f61b33)

### Minimal Theme (Bug?)
![Minimal Theme](https://github.com/efemkay/obsidian-modular-css-layout/assets/114118274/36358696-271e-4c53-8ed5-af329cafb373)

Not only does the layout change, the image is also "cropped" on the right.

All the themes I have tested act like the "Default Theme", it only happens with the Minimal Theme.

**Comment by efemkay** [comment]
hey @Rikiub can you share the raw markdown? i'm not sure what u mean by "multi-column by 3x3". don't have specific 3x3 setups. so far i've only 3 columns on single row or multi column multi row that will be responsive to your screensize (the smaller screen will have less columns)

**Comment by Rikiub** [comment]
Ah sorry, I was not very precise.

This is the Markdown:

```md
> [!multi-column]
> 
>> [!blank]
>> ![[image.jpg]]
>
>> [!blank]
>> ![[image.jpg]]
>
>> [!blank]
>> ![[image.jpg]]
>
>> [!blank]
>> ![[image.jpg]]
>
>> [!blank]
>> ![[image.jpg]]
```

**Comment by efemkay** [comment]
the number of columns is as per mentioned. it's dynamic based on sub-callout width setting (can change via style settings). the picture "cut off" is the same issue as per #50 . will work on the fix
