### ISSUE TITLE
BUG: After opening "wide", it will overlap with Banner

### ISSUE THREAD

**Issue by MugenLee** [efemkay/obsidian-modular-css-layout#5]
Your CSS snippets are very useful to me, I have achieved the idea of ​​building Homepage to a certain extent, thank you very much

But in the process of using, I found some problems, which are recorded as follows:

1. Floating CSS seems to have no effect, some issues have been raised (I also use the mini theme)

2. After using wide cssclass（page,dataview, table）, in reading mode, the content will overlap with Banner (I use Banner plugin)

Can you see what the problem is?
@efemkay 
Looking forward to the fix, this CSS snippet is really useful, thanks again~

![image](https://user-images.githubusercontent.com/91043731/166493301-fbc2f5a5-cbc1-4413-bb2b-363949fb3948.png)

**Comment by efemkay** [comment]
Thanks @MugenLee for highlighting the issue. Yeah i found out what's causing it and will roll out the fix very soon.

**Comment by MugenLee** [comment]
> 
Looking forward to the fix~

**Comment by efemkay** [comment]
i've updated the wide views snippet for the banner fix. redownload the snippet and have a go at it. lemme know if it's okay on your end

![image](https://user-images.githubusercontent.com/42369515/167055782-1dcfe914-d0fb-46ce-949c-aac92625936c.png)

**Comment by MugenLee** [comment]
> i've updated the wide views snippet for the banner fix. redownload the snippet and have a go at it. lemme know if it's okay on your end
> 
> ![image](https://user-images.githubusercontent.com/42369515/167055782-1dcfe914-d0fb-46ce-949c-aac92625936c.png)

thank Q~,it see OK 

but have some question, then the position of the emoji icon added with the Banner plugin seems to be offset after using the wide-page fragment

I recorded a gif, in which the position of the icon changed from center to below

You can take a look at it, if it can fix this problem, it will be perfect
![GIF 2022-5-6 11-40-22](https://user-images.githubusercontent.com/91043731/167063482-94aa381e-0508-4374-bc01-337588372399.gif)

**Comment by MugenLee** [comment]
> i've updated the wide views snippet for the banner fix. redownload the snippet and have a go at it. lemme know if it's okay on your end
> 
> ![image](https://user-images.githubusercontent.com/42369515/167055782-1dcfe914-d0fb-46ce-949c-aac92625936c.png)

Sorry, I found the cause of the problem. After the `breadcrumb plugin` is enabled to display the breadcrumb, the icon position is impressed. It has nothing to do with the css fragment. 

Please ignore this feedback.
