### ISSUE TITLE
`wide-page` very not-wide in Obsidian 1.4.5

### ISSUE THREAD

**Issue by nwpappas** [efemkay/obsidian-modular-css-layout#51]
Downloading latest version of MCL (zip says 0.9.5, source calls out 0.9.4) I added a `wide-page` to the `cssclasses` in Obsidian 1.4.5 and see the following not-so-wide-pade in edit mode:

![Screenshot 2023-08-31 at 3 28 37 PM](https://github.com/efemkay/obsidian-modular-css-layout/assets/2529208/6734919a-5c86-4a84-bae1-62295c2b5009)

The page is full width in view mode.

I have several snippets copied over from Minimal (I use the AnuPpuccin theme). I removed them all, keeping only MCL, but got the same result.

`wide-dataview` works with no other CSS:

![Screenshot 2023-08-31 at 4 01 26 PM](https://github.com/efemkay/obsidian-modular-css-layout/assets/2529208/5ee31365-8a94-4442-891d-657049375f16)

But collapses (in edit mode) when I add the Minimal CSS styles that provide for the `cards*` classes:

![Screenshot 2023-08-31 at 4 02 11 PM](https://github.com/efemkay/obsidian-modular-css-layout/assets/2529208/1a92787b-c557-4245-a82b-3b2e54311f72)

Works fine in view mode.

![Screenshot 2023-08-31 at 4 03 02 PM](https://github.com/efemkay/obsidian-modular-css-layout/assets/2529208/695a0da1-7466-40ff-b20f-93427f1acd72)

**Comment by albertoloscerritos** [comment]
Indeed. the wide snippet has a lot of bugs in the current version of obsidian. In my case it even affected notes that didn't even used the snippet (making them narrower for some reason) when toggling between notes.

**Comment by efemkay** [comment]
@nwpappas if u can list the other snippets you used would help me out. Cannot repro the issues you mentioned

@albertoloscerritos yeah the wide blocks (wide dataview, wide table) need to be reworked due to many changes in obsidian structure. I'm working on revamping the wide views snippet, but I will say that making wide blocks work in edit mode has become a bit more challenging (due to line numbering gutter). I'll tag this comment when I have a new release on it

**Comment by albertoloscerritos** [comment]
Thanks for keeping us up to date :)

**Comment by efemkay** [comment]
hey @nwpappas @albertoloscerritos  i've released update that's rewrite the entire wide page / wide blocks snippets. can u try and see if this also fix the issue u both have

**Comment by efemkay** [comment]
do reopen the issue if the problem somehow persists
