### ISSUE TITLE
Unnecessary whitespace around multi column callouts

### ISSUE THREAD

**Issue by gojzdar** [efemkay/obsidian-modular-css-layout#54]
As shown here:
![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/135328910/55bf11d6-fe68-4ba2-a2d4-4efe11e40488)
![image](https://github.com/efemkay/obsidian-modular-css-layout/assets/135328910/d9f79411-31ff-4466-a073-89d2366d842b)

Non multi-column callouts are wider than mutli-column ones.
It bothers me and takes up unnecessary space.

Other than that, the plugin does everything I need. Thank you.

**Comment by efemkay** [comment]
hi there. let me see if i can safely remove that space. i introduced it a long time ago some a reason. so want to check whether the reason is still valid or not

**Comment by efemkay** [comment]
enhancement released with v0.9.7
