### ISSUE TITLE
Properties Panel break with update to 0.9.5 + above

### ISSUE THREAD

**Issue by arfx** [efemkay/obsidian-modular-css-layout#57]
Hey, 
since I recently updated to the newest snippets files I noticed that the properties panel breaks with the minimal theme.
When I went back to 0.9.4 it still worked again, I also resisted my Style Settings before so that it could get from that.

https://github.com/efemkay/obsidian-modular-css-layout/assets/8065400/eb78372e-6b93-4af7-a8a0-6f32baa8bf4f

**Comment by efemkay** [comment]
hey @arfx that's a good screen capture. unfortunately i still cannot reproduce from my side. can u share with me ur debug info. u can extract that via Command Pallette i.e. `Cmd/Ctrl + P`, "Show debug info" > Click "Copy to clipboard" and then paste it here.

here's example from mine

```
SYSTEM INFO:
	Obsidian version: v1.4.15
	Installer version: v1.4.13
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v7.2.1
	Snippets enabled: 6
	Restricted mode: off
	Plugins installed: 40
	Plugins enabled: 13
		1: Another Quick Switcher v9.0.0
		2: Dataview v0.5.56
		3: MySnippets v1.2.3
		4: Style Settings v1.0.6
		5: Theme Design Utilities v0.21.1
		6: Theme Picker v1.0.8
		7: Outliner v4.8.0
		8: Omnisearch v1.17.1
		9: Better Search Views v0.2.2
		10: Snippet Downloader v2.0.1
		11: Obsidian42 - BRAT v0.7.0
		12: Query Control v0.6.0
		13: Advanced Tables v0.19.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Comment by arfx** [comment]
Hey, I wanted to upload just my Debug Infos and noticed when I compared mine to yours that my Community theme: Minimal was quite old 6.3. After updating this it worked great, sorry for raising that Bug. 

Totally my fault, next time I checked the theme itself as well, the rest I did but not the theme. 🙏

SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.14
	Operating system: Windows 10 Pro N 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Minimal v6.3.11
	Snippets enabled: 10
	Restricted mode: off
	Plugins installed: 14
	Plugins enabled: 14
		1: Custom File Explorer sorting v1.9.2
		2: Supercharged Links v0.10.3
		3: Contextual Typography v2.2.5
		4: Dataview v0.5.61
		5: Creases v0.7.0
		6: Commander v0.5.0
		7: Iconize v2.4.2
		8: Banners v1.3.3
		9: Excalidraw v1.9.23
		10: Heatmap Calendar v0.6.0
		11: Minimal Theme Settings v7.3.0
		12: Mousewheel Image zoom v1.0.19
		13: Simple Embeds v1.14.1
		14: Style Settings v1.0.7

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by arfx** [comment]
Can be closed.

**Comment by efemkay** [comment]
@arfx glad that got sorted out. but yeah, that's why i asked for the debug info. it's a quick way for me to figure out how to replicate if i can reproduce it
