### ISSUE TITLE
 Enhancement: wide-dataview fragment, increased width

### ISSUE THREAD

**Issue by MugenLee** [efemkay/obsidian-modular-css-layout#6]
hello， Wide-dataview is a very practical function. On pages with limited width, displaying DataView as much as possible is his meaning, great

I updated the latest css snippet and found that the width increase of the dataview is still limited, as the gif recorded below
![GIF 2022-5-6 11-49-37](https://user-images.githubusercontent.com/91043731/167064509-cc970163-88d8-4ab9-8b2b-7be692d38dde.gif)

But I found that using the `old version` of the css fragment, with the edit setting: `edit>Display>Readable line length: off`, yes, `off`, can stretch the width of the dataview table even the widest

as recorded gif
![GIF 2022-5-6 11-54-52](https://user-images.githubusercontent.com/91043731/167064818-464b2ef4-4940-4f86-869b-2dbeb577493e.gif)

After all, there are not a few users of `Readable line length: on`. I don't know the mechanism very well, but the display effect of this maximum width DataView is what I have always wanted to have, and **I believe this will greatly improve productivity**

so I hope:

Is it possible to turn on the wide-dataview fragment when `Readable line length: on`, and the dataview width can still be the widest?

Looking forward to your reply
@efemkay 
good luck

**Comment by efemkay** [comment]
minimal theme already has excellent control in this regard. i may still include in near future (support on custom block width for minimal theme), but i highly suggest use minimal's own settings i.e. `table-100` or `table-wide` (similarly, put them in the yaml). you may refer to minimal guide here (https://minimal.guide/Features/Block+width).

**Comment by MugenLee** [comment]
> minimal theme already has excellent control in this regard. i may still include in near future (support on custom block width for minimal theme), but i highly suggest use minimal's own settings i.e. `table-100` or `table-wide` (similarly, put them in the yaml). you may refer to minimal guide here (https://minimal.guide/Features/Block+width).
> 
> i'll keep this open until i have that feature support for minimal

thank you .
I have updated mini v5.2, it supports real-time rendering of dataview table maximum width under Live preview

At present, there are some bugs, that is, the width of the callout becomes strange at the same time, the author should optimize it

I would also use your CSS, because wide-page can be used to specify the page width of the document, which is very useful for making homepages

**Comment by efemkay** [comment]
i think i fixed it. give it a try n let me know

**Comment by MugenLee** [comment]
> i think i fixed it. give it a try n let me know


It should be fine, thanks for the update~
