### ISSUE TITLE
Center wide tables? 

### ISSUE THREAD

**Issue by ironhak** [efemkay/obsidian-modular-css-layout#69]
Hello! When I use cssclass wide-table the table is centered on reading view but on live-preview is aligned to the left. Is it possibile to have it centered so that live-preview and reading view are identical?

Thank's

**Comment by efemkay** [comment]
here there @ironhak , didn't realised it wasn't centered in LP. i always intent it to be centered. i will update the snippet for that. in the meanwhile, if u need the correction now, simply add the following lines

```
.wide-table .table-wrapper {
    margin-inline: auto;
}
```

**Comment by ironhak** [comment]
Thank's so much!!
I would also like to ask: is there a way to get in-app updates of your snippets? I see you're suggesting to use [Obsidian Snippet Downloader](https://github.com/Lisandra-dev/obsidian-snippet-downloader) but apparently it's not mantained anymore and also removed from plugin store.

Thank's again

**Comment by efemkay** [comment]
at the moment, i don't have other alternatives. you may install the plugin via BRAT (see link below) or manually download the snippets (steps as per link below as well)

https://efemkay.github.io/obsidian-modular-css-layout/installation/

**Comment by kazerniel** [comment]
> ```
> .wide-table .table-wrapper {
>     margin-inline: auto;
> }
> ```

unfortunately this does not work for me, wide-table is still left-aligned in live preview mode

**Comment by ironhak** [comment]
> > ```
> > .wide-table .table-wrapper {
> >     margin-inline: auto;
> > }
> > ```
> 
> unfortunately this does not work for me, wide-table is still left-aligned in live preview mode
> 
> Edit: I guess it's something to do with the global toggle? With that one it stays left aligned, but with the class being set on the individual page, it's centred 🤔

It used to work, apparently recent updates broke it... Anyone knows a solution?

**Comment by ironhak** [comment]
Solution:
```
table, .table-wrapper  {
    margin-inline: auto;
}
```

**Comment by elvarb** [comment]
This fix works if I set it as a separate css

Using only the css in [MCL Wide Views.css](https://github.com/efemkay/obsidian-modular-css-layout/blob/main/MCL%20Wide%20Views.css) the tables get aligned to the left.
