### ISSUE TITLE
Overlapping elements in backlinks 

### ISSUE THREAD

**Issue by rubaboo** [efemkay/obsidian-modular-css-layout#75]
Wondering if I should have a snippet to add a `min-width` to `.embedded-backlinks` or `.cm-sizer`, or if there is an even better way to visually separate the button bar from text.

<img src="https://github.com/efemkay/obsidian-modular-css-layout/assets/212368/0cfe8d9a-96f7-4554-8655-1c81d3575b09" width="200">

**Comment by efemkay** [comment]
is that in reference my snippets? i tested with sandbox vault, and the behaviour is there.
