### ISSUE TITLE
Indentation in mcl/list-card appeared

### ISSUE THREAD

**Issue by Pummelfisch** [efemkay/obsidian-modular-css-layout#89]
Since v1.6 the mcl/list-card view now indents its objects resulting in a weird looking space left to images and text fields. See image below (I've marked two of those areas i mean)
![2024-05-15T18:55:29,672175256+02:00](https://github.com/efemkay/obsidian-modular-css-layout/assets/67376951/5a68d1ab-5a7e-42b8-9852-540d6cd34997)

**Comment by efemkay** [comment]
pushed fixes on this
