### ISSUE TITLE
[Feature request] mobile support

### ISSUE THREAD

**Issue by mrazarny** [efemkay/obsidian-modular-css-layout#93]
currently both multi column layout and floating callout are not working mobile 

those are the one i tested not sure about wide views 

even in the github here the example photo of the multi column appears like regular callouts stacked above each other in mobile

so, im asking if its *possible* to make the css work on mobile as pc 

and for some example of how i wish it to be pls refer to multi-column-markdown plugin

**Comment by efemkay** [comment]
It definitely does support mobile. But I make it responsive - it follows the available space. There's a minimum width required for the multi column callout to work. Else things will be too cramped 

Here's a screenshot from my phone but I have to tilt it horizontally. If it were vertical, the layout will resort to stack up and down.

![Screenshot_20240714_170151_Obsidian.jpg](https://github.com/user-attachments/assets/5172f59e-4acd-45e6-94b8-c4a0164f3182)

**Comment by mrazarny** [comment]
ah i didn't know that 

ty for replying but i would also recommend to make the width thing as a feature u can turn off in style settings or by using special syntax for special callout that u always want to see as column 

that would be better for special cases its just a recommendation it the end 

+ i wanted to know how the multi column works on mobile so i though of sybmitting this issue 

u can close it if u wanna or think about my recommendation it's up to u 

have a nice day mate :)

**Comment by mrazarny** [comment]
u probably forget about me but when i checked the snippet repo i found out that u made a new version with the no wrap feature which fixed my problem perfectly ty for these great snippets 

i think my problem is fixed so 

CASE CLOSED.
